source 'http://rubygems.org'

gem 'sinatra'
gem 'rack-flash'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-migrations'
gem 'dm-timestamps'
gem 'twitter_oauth', '0.4.1'
gem 'oauth', '0.3.6'
gem 'haml'
gem 'hashie'
